name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: git branch
      - run: echo "M2_HOME=$(dirname $(dirname `which mvn`))" >> $GITHUB_ENV
      - run: git config --global user.email "githubactions@example.com"
      - run: git config --global user.name "Github Actions"

      - name: Verify build
        run: mvn -DskipTests=true --batch-mode verify