name: Publish package to the Maven Central Repository
on:
  push

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          echo curl it
          curl -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'accept: */*' https://api.github.com/user
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Before settings.xml
        run: |
          cat ~/.m2/settings.xml
      - name: Set up maven setings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            }]
      - name: After settings.xml
        run: |
          cat ~/.m2/settings.xml
      - name: Verify package
        run: mvn --no-transfer-progress --batch-mode verify
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release package
        run: mvn --no-transfer-progress --batch-mode -DskipTests=true releaser:release
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
